"""create parse_job and document_parse_result tables

Revision ID: 2c0d84234526
Revises: b3c4951a4fb2
Create Date: 2026-06-15 06:26:16.907688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0d84234526'
down_revision: Union[str, Sequence[str], None] = 'b3c4951a4fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('input_path', sa.String(length=500), nullable=False),
    sa.Column('output_dir', sa.String(length=500), nullable=True),
    sa.Column('backend', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parse_job_contract_id'), 'parse_job', ['contract_id'], unique=False)
    op.create_table('document_parse_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('parse_job_id', sa.Integer(), nullable=False),
    sa.Column('markdown_path', sa.String(length=500), nullable=True),
    sa.Column('content_json_path', sa.String(length=500), nullable=True),
    sa.Column('middle_json_path', sa.String(length=500), nullable=True),
    sa.Column('layout_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('image_dir', sa.String(length=500), nullable=True),
    sa.Column('raw_markdown', sa.Text(), nullable=True),
    sa.Column('normalized_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['parse_job_id'], ['parse_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_parse_result_contract_id'), 'document_parse_result', ['contract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_parse_result_contract_id'), table_name='document_parse_result')
    op.drop_table('document_parse_result')
    op.drop_index(op.f('ix_parse_job_contract_id'), table_name='parse_job')
    op.drop_table('parse_job')
    # ### end Alembic commands ###
