"""create contract_clause risk_item modify_suggestion review_report tables

Revision ID: 3f71af593ebc
Revises: 62c0e4d126d3
Create Date: 2026-06-15 09:05:44.799507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f71af593ebc'
down_revision: Union[str, Sequence[str], None] = '62c0e4d126d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_clause',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('clause_id', sa.String(length=32), nullable=False),
    sa.Column('section_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('clause_type', sa.String(length=64), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['review_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_clause_task_id'), 'contract_clause', ['task_id'], unique=False)
    op.create_table('modify_suggestion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.String(length=32), nullable=False),
    sa.Column('risk_id', sa.String(length=32), nullable=True),
    sa.Column('clause_id', sa.String(length=32), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('suggested_text', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['review_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modify_suggestion_task_id'), 'modify_suggestion', ['task_id'], unique=False)
    op.create_table('review_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('report_title', sa.String(length=255), nullable=True),
    sa.Column('overall_risk', sa.String(length=32), nullable=True),
    sa.Column('markdown_report', sa.Text(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['review_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_report_task_id'), 'review_report', ['task_id'], unique=False)
    op.create_table('risk_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.String(length=32), nullable=False),
    sa.Column('clause_id', sa.String(length=32), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('risk_type', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('need_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['review_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_item_task_id'), 'risk_item', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_item_task_id'), table_name='risk_item')
    op.drop_table('risk_item')
    op.drop_index(op.f('ix_review_report_task_id'), table_name='review_report')
    op.drop_table('review_report')
    op.drop_index(op.f('ix_modify_suggestion_task_id'), table_name='modify_suggestion')
    op.drop_table('modify_suggestion')
    op.drop_index(op.f('ix_contract_clause_task_id'), table_name='contract_clause')
    op.drop_table('contract_clause')
    # ### end Alembic commands ###
