"""create review_task and agent_execution_log tables

Revision ID: 62c0e4d126d3
Revises: 2c0d84234526
Create Date: 2026-06-15 08:31:49.835492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c0e4d126d3'
down_revision: Union[str, Sequence[str], None] = '2c0d84234526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_task_contract_id'), 'review_task', ['contract_id'], unique=False)
    op.create_index(op.f('ix_review_task_user_id'), 'review_task', ['user_id'], unique=False)
    op.create_table('agent_execution_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['review_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_execution_log_task_id'), 'agent_execution_log', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_execution_log_task_id'), table_name='agent_execution_log')
    op.drop_table('agent_execution_log')
    op.drop_index(op.f('ix_review_task_user_id'), table_name='review_task')
    op.drop_index(op.f('ix_review_task_contract_id'), table_name='review_task')
    op.drop_table('review_task')
    # ### end Alembic commands ###
